name: Docker Lint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Verify Docker Compose
      run: |
        docker --version
        docker compose version
        
    - name: Build the Docker Compose stack
      run: |
        docker compose build
        docker compose config